baseurl = "http://SeungKiLeeSMU.github.io"
title = "SeungKi Lee"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[--> Software Engineer, Economist, Writer <!--]-->'
  logo = "fa-code"
  copyright = "SeungKi Lee"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "#"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "http://github.com/SeungKiLeeSMU"


[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.ko]
languageName = "Korean"
weight = 2
description = '<!--[--> 파편을 심는 화분 <!--]--> </br>
                  <!--[--> 프로그래머, 경제학자, 작가 <!--]-->'

[languages.jp]
languageName = "Japanese"
weight = 3
description = '<!--[--> 破片を植えるプランター <!--]-->'
